image: maven:3.6.3-jdk-11

cache:
  paths:
    - .m2/repostiory

before_script:
  - cd $CI_PROJECT_DIR && cd ..

after_script:
  - cd $CI_PROJECT_DIR && cd ..

stages:
  - build
  - test # no tests implemented
  - package
  - publish
  - deploy

service-registry:build:
  stage: build
  script:
    - cd service-registry/ && mvn clean compile
  only:
    changes:
      - service-registry/**/*


service-registry:test:
  stage: test
  script:
    - cd service-registry/ && mvn test
  only:
    changes:
      - service-registry/**/*


service-registry:package:
  stage: package
  script:
    - cd service-registry/ && mvn package -DskipTests=true
  artifacts:
    paths:
      - service-registry/target/*.jar
  only:
    changes:
      - service-registry/**/*


service-registry:publish:
  stage: publish
  image: docker:stable

  script:
    - cd service-registry
    - docker login -u $CI_REGISTRY_USER -p $CI_PASSWORD $CI_REGISTRY
    - docker build -t $SR_IMAGE_NAME:latest .
    - docker image tag $SR_IMAGE_NAME $CI_REGISTRY/$CI_PROJECT_LOCATION:$SR_IMAGE_NAME
    - docker push $CI_REGISTRY/$CI_PROJECT_LOCATION:$SR_IMAGE_NAME
  variables:
    SR_IMAGE_NAME: service-registry
  only:
    changes:
      - service-registry/*/**


